# Generated by Django 2.2.6 on 2019-10-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_off', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('nutritional_score', models.CharField(max_length=2)),
                ('url', models.URLField()),
                ('ingredients', models.TextField()),
                ('purchase_place', models.CharField(max_length=200)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments_off.Category')),
            ],
        ),
    ]
