# Generated by Django 2.2.6 on 2019-11-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliments_off', '0003_auto_20191028_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
